### ISSUE TITLE
Errors on clean install (master/1.0)

### ISSUE THREAD

**Issue by Noisecommander** [bellydrum/akai-mpd226-midi-control#4]
Hey they,

I'm not getting any functinalliy yet, and I'm getting errors in FL's _Script output_ interface with both MIDI Control's **1.0** release and the current **master**.

Are you interested in the output from any specific version?

**Comment by bellydrum** [comment]
@Noisecommander what errors are you getting?

I know for a fact that all the string formatting will cause errors, due to FL not handling modern Python string formatting. Because of this, I've started changing all the strings to use older formatting.

If you show me your errors I'll work on fixing it.

**Comment by Noisecommander** [comment]
Sure thing, this is the entire output of the current master branch:

```
FL Studio Midi scripting version: 8
"C:\Users\<Username>\Documents\Image-Line\FL Studio\Settings\Hardware\Akai MPD226\device_AkaiMPD226.py" found

init ok
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\<Username>\Documents\Image-Line\FL Studio\Settings\Hardware\Akai MPD226\MPDHandler.py", line 70
    print({button.type.upper()+ " " + str(button.number) + " has no associated buffer.")
                                                                                       ^
SyntaxError: invalid syntax

```

**Comment by bellydrum** [comment]
@Noisecommander Thanks, that's a syntax error on my part that I've fixed in the [latest commit](https://github.com/bellydrum/akai-mpd226-midi-control/commit/f8a0777c3659a97b75b43e40822fe035390a88cb).
